language: generic
matrix:
  allow_failures:
    - os: linux
  include:
    - os: linux
      services: docker
      sudo: required
      dist: trusty
    - os: osx
      osx_image: xcode7.3
      sudo: required
install: eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"
script:
  - echo ">> Let's build and test the '$TRAVIS_BRANCH' branch for Ngram."
  - make travis
  - echo ">> Build and tests completed. See above for status."
branches:
  only:
    - master
    - develop
